### ISSUE TITLE
Account transfer issue

### ISSUE THREAD

**Issue by BlasterGrim** [FlashChaser/Open-Source-Battle-Bot#104]
First I would like to congratulate with you for the great job,
so i've 2 questions about that,
1) After create an account and linked to the app with ID, i cannot reconnect with bot, because program show:

Traceback (most recent call last):

  File "dokkan.py", line 51, in <module>
  File "commands.py", line 2024, in load_account
  File "commands.py", line 1564, in refresh_client
TypeError: cannot unpack non-iterable NoneType object
[28476] Failed to execute script dokkan

you know why?

2) How can i transfer an account into this bot?
i've tried a lot of time with different account ID but the response from program was:

URL: http://ishin-production.aktsk.jp/auth/link_codes/*here is account ID*
{'error': {'code': 'oauth2_mac_rails/link_code_not_found'}}
Traceback (most recent call last):
  File "dokkan.py", line 47, in <module>
  File "commands.py", line 2202, in transfer_account
KeyError: 'identifiers'
[30840] Failed to execute script dokkan

Could you help me?
Thank's in advance

**Comment by BlasterGrim** [comment]
i'm using lastest software version, 0.1.1
