### ISSUE TITLE
Completeevents gives a name error when trying to execute in daily login/bulk login

### ISSUE THREAD

**Issue by NilBarua** [FlashChaser/Open-Source-Battle-Bot#127]
When I try to execute the bulk login command 'completeevents' then it logins to the account shows the stage and shows this error. My Global database is up to date. Completing Z Battles does work though.

Please let me know how to solve this.

**ERROR CODE**
**_Begin stage: STR Hidden Potential Event 143001 | Difficulty: 2 Deck: 1
Traceback (most recent call last):
  File "dokkan.py", line 83, in <module>
    commands.bulk_daily_logins()
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 4614, in bulk_daily_logins
    bulk_daily_save_processor(file, login, gift, daily_events, user_input)
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 4647, in bulk_daily_save_processor
    user_command_executor(user_input)
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 2723, in user_command_executor
    complete_unfinished_events()
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 2141, in complete_unfinished_events
    complete_stage(str(stage['sugoroku_map_id'])[:-1], str(stage['sugoroku_map_id'])[-1])
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 65, in complete_stage
    random.choice(list('abcdefghijklmnopqrstuvwxyzBCDEFGHIKLMNOPQRUVWXYZ123456789-_')) for i in range(63))
  File "C:\Users\Nil\Desktop\BotFarm\commands.py", line 65, in <genexpr>
    random.choice(list('abcdefghijklmnopqrstuvwxyzBCDEFGHIKLMNOPQRUVWXYZ123456789-_')) for i in range(63))
NameError: name 'random' is not defined_**

**Comment by NilBarua** [comment]
I just tried the **completequests** command as well and it gives the error: **name: 'random' is not defined**

**Comment by K1mpl0s** [comment]
once you merge the PR, you may close this. @FlashChaser

**Comment by NilBarua** [comment]
Edit the insert random into the commands.py file and you should be ready.
